**Import Libraries:**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

**Upload the file**

In [ ]:
df_movies=pd.read_csv("/content/movie_metadata.csv")
org_data=df_movies

In [ ]:
df_movies.head(2)   # Display top 2 records

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0

In [ ]:
df_movies.shape   # To show shape of the dataframe

(5043, 28)

In [ ]:
df_movies.info()   # Display information abt dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   color                      5024 non-null   object
 1   director_name              4939 non-null   object
 2   num_critic_for_reviews     4993 non-null   float64
 3   duration                   5028 non-null   float64
 4   director_facebook_likes    4939 non-null   float64
 5   actor_3_facebook_likes     5020 non-null   float64
 6   actor_2_name               5030 non-null   object
 7   actor_1_facebook_likes     5036 non-null   float64
 8   gross                      4159 non-null   float64
 9   genres                     5043 non-null   object
 10  actor_1_name               5036 non-null   object
 11  movie_title                5043 non-null   object
 12  num_voted_users            5043 non-null   int64
 13  cast_total_facebook_likes  5043 non-null   int64
 14  actor_3_name               5020 non-null   object
 15  facenumber_in_poster       5030 non-null   float64
 16  plot_keywords              4890 non-null   object
 17  movie_imdb_link            5043 non-null   object
 18  num_user_for_reviews       5022 non-null   float64
 19  language                   5031 non-null   object
 20  country                    5038 non-null   object
 21  content_rating             4740 non-null   object
 22  budget                     4551 non-null   float64
 23  title_year                 4935 non-null   float64
 24  actor_2_facebook_likes     5030 non-null   float64
 25  imdb_score                 5043 non-null   float64
 26  aspect_ratio               4714 non-null   float64
 27  movie_facebook_likes       5043 non-null   int64
dtypes: float64(13), int64(3), object(12)
memory usage: 1.1+ MB

**Cleaning Data**

In [ ]:
df_movies.isnull().sum().sort_values(ascending=False)  # Find the missing values column wise

gross                        884
budget                       492
aspect_ratio                 329
content_rating               303
plot_keywords                153
title_year                   108
director_name                104
director_facebook_likes      104
num_critic_for_reviews        50
actor_3_name                  23
actor_3_facebook_likes        23
num_user_for_reviews          21
color                         19
duration                      15
facenumber_in_poster          13
actor_2_name                  13
actor_2_facebook_likes        13
language                      12
actor_1_name                   7
actor_1_facebook_likes         7
country                        5
cast_total_facebook_likes      0
num_voted_users                0
movie_title                    0
movie_imdb_link                0
genres                         0
imdb_score                     0
movie_facebook_likes           0
dtype: int64

In [ ]:
df_movies.isnull().sum(axis=1).sort_values(ascending=False)  # Find the missing values row wise

279     15
4       14
4945    11
2241    11
2342    10
        ..
1703     0
1702     0
1701     0
1700     0
5042     0
Length: 5043, dtype: int64

In [ ]:
df_movies.isnull().sum().sort_values(ascending=False)/len(df_movies)*100   # find column wise null percentage

gross                        17.529248
budget                        9.756098
aspect_ratio                  6.523895
content_rating                6.008328
plot_keywords                 3.033908
title_year                    2.141582
director_name                 2.062265
director_facebook_likes       2.062265
num_critic_for_reviews        0.991473
actor_3_name                  0.456078
actor_3_facebook_likes        0.456078
num_user_for_reviews          0.416419
color                         0.376760
duration                      0.297442
facenumber_in_poster          0.257783
actor_2_name                  0.257783
actor_2_facebook_likes        0.257783
language                      0.237954
actor_1_name                  0.138806
actor_1_facebook_likes        0.138806
country                       0.099147
cast_total_facebook_likes     0.000000
num_voted_users               0.000000
movie_title                   0.000000
movie_imdb_link               0.000000
genres                        0.000000
imdb_score                    0.000000
movie_facebook_likes          0.000000
dtype: float64

### **Drop the unnecessasry columns**

In [ ]:
df_movies=df_movies.drop([
    'color','director_facebook_likes','actor_3_facebook_likes','actor_1_facebook_likes','actor_2_facebook_likes',
    'cast_total_facebook_likes','facenumber_in_poster','content_rating','plot_keywords',
    'actor_2_name','actor_3_name','duration','aspect_ratio','movie_imdb_link','country'
],axis=1)

In [ ]:
df_movies.shape

(5043, 13)

### **Drop unnecessary rows**

In [ ]:
# Drop unnecessary rows (rows which have more null values)
round(df_movies.isnull().sum().sort_values(ascending=False)/len(df_movies)*100,2)

gross                     17.53
budget                     9.76
title_year                 2.14
director_name              2.06
num_critic_for_reviews     0.99
num_user_for_reviews       0.42
language                   0.24
actor_1_name               0.14
genres                     0.00
movie_title                0.00
num_voted_users            0.00
imdb_score                 0.00
movie_facebook_likes       0.00
dtype: float64

In [ ]:
# Clean the data of columns gross and budget
df_movies=df_movies[df_movies['gross'].notnull()]
df_movies=df_movies[df_movies['budget'].notnull()]

In [ ]:
# Again check the data of rows (rows which have more null values)
round(df_movies.isnull().sum().sort_values(ascending=False)/len(df_movies)*100,2)

actor_1_name              0.08
language                  0.08
num_critic_for_reviews    0.03
director_name             0.00
gross                     0.00
genres                    0.00
movie_title               0.00
num_voted_users           0.00
num_user_for_reviews      0.00
budget                    0.00
title_year                0.00
imdb_score                0.00
movie_facebook_likes      0.00
dtype: float64

In [ ]:
df_movies.isnull().sum(axis=1).sort_values(ascending=False)   # Check the null values of rows

4502    1
4720    1
4110    1
4837    1
4711    1
       ..
1375    0
1376    0
1377    0
1378    0
5042    0
Length: 3891, dtype: int64

In [ ]:
# Check the null values of rows which have more than 5
(df_movies.isnull().sum(axis=1).sort_values(ascending=False)>5).sum()

0

In [ ]:
df_movies=df_movies[df_movies.isnull().sum(axis=1).sort_values(ascending=False)<=5]

<ipython-input-17-eb72336f3e13>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_movies=df_movies[df_movies.isnull().sum(axis=1).sort_values(ascending=False)<=5]

### **Fill NAN Values**

In [ ]:
round(df_movies.isnull().sum().sort_values(ascending=False)/len(df_movies)*100,2)

actor_1_name              0.08
language                  0.08
num_critic_for_reviews    0.03
director_name             0.00
gross                     0.00
genres                    0.00
movie_title               0.00
num_voted_users           0.00
num_user_for_reviews      0.00
budget                    0.00
title_year                0.00
imdb_score                0.00
movie_facebook_likes      0.00
dtype: float64

In [ ]:
df_movies['language'].value_counts().nlargest(5)

English     3707
French        37
Spanish       26
Mandarin      15
German        13
Name: language, dtype: int64

In [ ]:
df_movies.language.describe()

count        3888
unique         38
top       English
freq         3707
Name: language, dtype: object

**Observations:** Here total 3888 movies in that 3707 movies are English movies remaining movies are related to different(37) languages.

In [ ]:
df_movies.language=df_movies.language.fillna('English')

In [ ]:
round(df_movies.isnull().sum().sort_values(ascending=False)/len(df_movies)*100,2)

actor_1_name              0.08
num_critic_for_reviews    0.03
director_name             0.00
gross                     0.00
genres                    0.00
movie_title               0.00
num_voted_users           0.00
num_user_for_reviews      0.00
language                  0.00
budget                    0.00
title_year                0.00
imdb_score                0.00
movie_facebook_likes      0.00
dtype: float64

###**Check the number of retained rows**

You might notice that two of the columns num_critic_for_reviews and actor_1_name have small percentage of NaN valuesleft. You can let these columns as it is for now.Check the number and percentage of the rows retained after completing all the tasks above.

In [ ]:
len(df_movies)

3891

In [ ]:
# Checking the no.of  retained rows here ( retained meaning-continue to hold )
round(len(df_movies)/len(org_data)*100,2)

77.16

**Observarions:** You might have noticed that we still have around 77% of rows.

## **Data Analysis**

**Change the unit of columns**

In [ ]:
df_movies['budget']/1000000

0       237.0000
1       300.0000
2       245.0000
3       250.0000
5       263.7000
          ...
5033      0.0070
5034      0.0070
5035      0.0070
5037      0.0090
5042      0.0011
Name: budget, Length: 3891, dtype: float64

In [ ]:
# Convert the unit of the budget and gross columns from $ to million $
df_movies['budget']=df_movies['budget']/1000000
df_movies['gross']=df_movies['gross']/1000000

**Find the movies with highest profit**

Create a new column called profit which contains differece of the two columns gross and budget

In [ ]:
df_movies['profit']=df_movies['gross']-df_movies['budget']
df_movies

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0000,2009.0,7.9,33000,523.505847
1,Gore Verbinski,302.0,309.404152,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300.0000,2007.0,7.1,0,9.404152
2,Sam Mendes,602.0,200.074175,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245.0000,2015.0,6.8,85000,-44.925825
3,Christopher Nolan,813.0,448.130642,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250.0000,2012.0,8.5,164000,198.130642
5,Andrew Stanton,462.0,73.058679,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263.7000,2012.0,6.6,24000,-190.641321
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5033,Shane Carruth,143.0,0.424760,Drama|Sci-Fi|Thriller,Shane Carruth,Primer,72639,371.0,English,0.0070,2004.0,7.0,19000,0.417760
5034,Neill Dela Llana,35.0,0.070071,Thriller,Ian Gamazon,Cavite,589,35.0,English,0.0070,2005.0,6.3,74,0.063071
5035,Robert Rodriguez,56.0,2.040920,Action|Crime|Drama|Romance|Thriller,Carlos Gallardo,El Mariachi,52055,130.0,Spanish,0.0070,1992.0,6.9,0,2.033920
5037,Edward Burns,14.0,0.004584,Comedy|Drama,Kerry BishÃ©,Newlyweds,1338,14.0,English,0.0090,2011.0,6.4,413,-0.004416
5042,Jon Gunn,43.0,0.085222,Documentary,John August,My Date with Drew,4285,84.0,English,0.0011,2004.0,6.6,456,0.084122

**Observations:** Here we see a new column profit added at end ot the data set.In profit some values shown in negative means the movies which got loss.

In [ ]:
# Set the dataframe using the profit column as reference.
df_movies.sort_values(by='profit',ascending=False)

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.000000,2009.0,7.9,33000,523.505847
29,Colin Trevorrow,644.0,652.177271,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150.000000,2015.0,7.0,150000,502.177271
26,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.000000,1997.0,7.7,26000,458.672302
3024,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.000000,1977.0,8.7,33000,449.935665
3080,Steven Spielberg,215.0,434.949459,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10.500000,1982.0,7.9,34000,424.449459
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2334,Katsuhiro Ã”tomo,105.0,0.410388,Action|Adventure|Animation|Family|Sci-Fi|Thriller,William Hootkins,Steamboy,13727,79.0,Japanese,2127.519898,2004.0,6.9,973,-2127.109510
2323,Hayao Miyazaki,174.0,2.298191,Adventure|Animation|Fantasy,Minnie Driver,Princess Mononoke,221552,570.0,Japanese,2400.000000,1997.0,8.4,11000,-2397.701809
3005,Lajos Koltai,73.0,0.195888,Drama|Romance|War,Marcell Nagy,Fateless,5603,45.0,Hungarian,2500.000000,2005.0,7.1,607,-2499.804112
3859,Chan-wook Park,202.0,0.211667,Crime|Drama,Min-sik Choi,Lady Vengeance,53508,131.0,Korean,4200.000000,2005.0,7.7,4000,-4199.788333
2988,Joon-ho Bong,363.0,2.201412,Comedy|Drama|Horror|Sci-Fi,Doona Bae,The Host,68883,279.0,Korean,12215.500000,2006.0,7.0,7000,-12213.298588

In [ ]:
#Extract the top ten profiting movies in descending order and store them in a new dataframe-top10
top10 =df_movies.sort_values(by='profit',ascending=False).head(10)
top10

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0,2009.0,7.9,33000,523.505847
29,Colin Trevorrow,644.0,652.177271,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150.0,2015.0,7.0,150000,502.177271
26,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.0,1997.0,7.7,26000,458.672302
3024,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.0,1977.0,8.7,33000,449.935665
3080,Steven Spielberg,215.0,434.949459,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10.5,1982.0,7.9,34000,424.449459
794,Joss Whedon,703.0,623.279547,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.0,2012.0,8.1,123000,403.279547
17,Joss Whedon,703.0,623.279547,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.0,2012.0,8.1,123000,403.279547
509,Roger Allers,186.0,422.783777,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,The Lion King,644348,656.0,English,45.0,1994.0,8.5,17000,377.783777
240,George Lucas,320.0,474.544677,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode I - The Phantom Menace,534658,3597.0,English,115.0,1999.0,6.5,13000,359.544677
66,Christopher Nolan,645.0,533.316061,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185.0,2008.0,9.0,37000,348.316061

**Observations:** After you found out top 10 movies, you might have noticed duplicate values at row 17 and 794. It seems the dataframe has duplicate values as well.Drop the duplicate values.

###Drop Duplicate Values

In [ ]:
df_movies.drop_duplicates(keep='first',inplace=True)

In [ ]:
df_movies.shape

(3856, 14)

##Find IMDB Top 250

Create the new dataframe IMDB_Top_250 and store the top 250 movies with highest IMDB rating(corresponding the column imdb_score). Also make sure that all of these movies num_voted_users greater than 25000.Also add a rank column containing the values 1 to 250 indicating the ranks of the corresponding films.

In [ ]:
IMDB_Top_250 =df_movies[df_movies['num_voted_users']>25000].sort_values(by='imdb_score',ascending=False).head(250)
IMDB_Top_250

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
1937,Frank Darabont,199.0,28.341469,Crime|Drama,Morgan Freeman,The Shawshank Redemption,1689764,4144.0,English,25.00,1994.0,9.3,108000,3.341469
3466,Francis Ford Coppola,208.0,134.821952,Crime|Drama,Al Pacino,The Godfather,1155770,2238.0,English,6.00,1972.0,9.2,43000,128.821952
2837,Francis Ford Coppola,149.0,57.300000,Crime|Drama,Robert De Niro,The Godfather: Part II,790926,650.0,English,13.00,1974.0,9.0,14000,44.300000
66,Christopher Nolan,645.0,533.316061,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185.00,2008.0,9.0,37000,348.316061
4498,Sergio Leone,181.0,6.100000,Western,Clint Eastwood,"The Good, the Bad and the Ugly",503509,780.0,Italian,1.20,1966.0,8.9,20000,4.900000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4931,John Carney,232.0,9.437933,Drama|Music|Romance,Glen Hansard,Once,90827,329.0,English,0.18,2007.0,7.9,26000,9.257933
2605,Ang Lee,287.0,128.067808,Action|Drama|Romance,Chen Chang,"Crouching Tiger, Hidden Dragon",217740,1641.0,Mandarin,15.00,2000.0,7.9,0,113.067808
3029,David O. Russell,410.0,93.571803,Biography|Drama|Sport,Christian Bale,The Fighter,275869,389.0,English,25.00,2010.0,7.9,36000,68.571803
2177,Tim Burton,111.0,56.362352,Fantasy|Romance,Johnny Depp,Edward Scissorhands,357581,588.0,English,20.00,1990.0,7.9,16000,36.362352
2487,George Cukor,82.0,72.000000,Drama|Family|Musical|Romance,Jeremy Brett,My Fair Lady,66959,258.0,English,17.00,1964.0,7.9,0,55.000000

In [ ]:
# Add a new column called Rank
IMDB_Top_250['Rank']=IMDB_Top_250['imdb_score'].rank(method='first',ascending=False)
IMDB_Top_250

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,Rank
1937,Frank Darabont,199.0,28.341469,Crime|Drama,Morgan Freeman,The Shawshank Redemption,1689764,4144.0,English,25.00,1994.0,9.3,108000,3.341469,1.0
3466,Francis Ford Coppola,208.0,134.821952,Crime|Drama,Al Pacino,The Godfather,1155770,2238.0,English,6.00,1972.0,9.2,43000,128.821952,2.0
2837,Francis Ford Coppola,149.0,57.300000,Crime|Drama,Robert De Niro,The Godfather: Part II,790926,650.0,English,13.00,1974.0,9.0,14000,44.300000,3.0
66,Christopher Nolan,645.0,533.316061,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185.00,2008.0,9.0,37000,348.316061,4.0
4498,Sergio Leone,181.0,6.100000,Western,Clint Eastwood,"The Good, the Bad and the Ugly",503509,780.0,Italian,1.20,1966.0,8.9,20000,4.900000,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4931,John Carney,232.0,9.437933,Drama|Music|Romance,Glen Hansard,Once,90827,329.0,English,0.18,2007.0,7.9,26000,9.257933,246.0
2605,Ang Lee,287.0,128.067808,Action|Drama|Romance,Chen Chang,"Crouching Tiger, Hidden Dragon",217740,1641.0,Mandarin,15.00,2000.0,7.9,0,113.067808,247.0
3029,David O. Russell,410.0,93.571803,Biography|Drama|Sport,Christian Bale,The Fighter,275869,389.0,English,25.00,2010.0,7.9,36000,68.571803,248.0
2177,Tim Burton,111.0,56.362352,Fantasy|Romance,Johnny Depp,Edward Scissorhands,357581,588.0,English,20.00,1990.0,7.9,16000,36.362352,249.0
2487,George Cukor,82.0,72.000000,Drama|Family|Musical|Romance,Jeremy Brett,My Fair Lady,66959,258.0,English,17.00,1964.0,7.9,0,55.000000,250.0

Extract all the movies in the IMDB_Top_250 dataframe which are not in the English language and store them in a new dataframe named **Top_Foreign_lang_film**

In [ ]:
Top_Foreign_lang_film=IMDB_Top_250[IMDB_Top_250['language']!='English']
Top_Foreign_lang_film

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,Rank
4498,Sergio Leone,181.0,6.100000,Western,Clint Eastwood,"The Good, the Bad and the Ugly",503509,780.0,Italian,1.200000,1966.0,8.9,20000,4.900000,5.0
4747,Akira Kurosawa,153.0,0.269061,Action|Adventure|Drama,Takashi Shimura,Seven Samurai,229012,596.0,Japanese,2.000000,1954.0,8.7,11000,-1.730939,17.0
4029,Fernando Meirelles,214.0,7.563397,Crime|Drama,Alice Braga,City of God,533200,749.0,Portuguese,3.300000,2002.0,8.7,28000,4.263397,20.0
2373,Hayao Miyazaki,246.0,10.049886,Adventure|Animation|Family|Fantasy,Bunta Sugawara,Spirited Away,417971,902.0,Japanese,19.000000,2001.0,8.6,28000,-8.950114,23.0
4259,Florian Henckel von Donnersmarck,215.0,11.284657,Drama|Thriller,Sebastian Koch,The Lives of Others,259379,407.0,German,2.000000,2006.0,8.5,39000,9.284657,35.0
4921,Majid Majidi,46.0,0.925402,Drama|Family,Bahare Seddiqi,Children of Heaven,27882,130.0,Persian,0.180000,1997.0,8.5,0,0.745402,39.0
2323,Hayao Miyazaki,174.0,2.298191,Adventure|Animation|Fantasy,Minnie Driver,Princess Mononoke,221552,570.0,Japanese,2400.000000,1997.0,8.4,11000,-2397.701809,47.0
2970,Wolfgang Petersen,96.0,11.433134,Adventure|Drama|Thriller|War,JÃ¼rgen Prochnow,Das Boot,168203,426.0,German,14.000000,1981.0,8.4,11000,-2.566866,49.0
4105,Chan-wook Park,305.0,2.181290,Drama|Mystery|Thriller,Min-sik Choi,Oldboy,356181,809.0,Korean,3.000000,2003.0,8.4,43000,-0.818710,57.0
4659,Asghar Farhadi,354.0,7.098492,Drama|Mystery,Shahab Hosseini,A Separation,151812,264.0,Persian,0.500000,2011.0,8.4,48000,6.598492,58.0
1329,S.S. Rajamouli,44.0,6.498000,Action|Adventure|Drama|Fantasy|War,Tamannaah Bhatia,Baahubali: The Beginning,62756,410.0,Telugu,18.026148,2015.0,8.4,21000,-11.528148,59.0
1298,Jean-Pierre Jeunet,242.0,33.201661,Comedy|Romance,Mathieu Kassovitz,AmÃ©lie,534262,1314.0,French,77.000000,2001.0,8.4,39000,-43.798339,61.0
2734,Fritz Lang,260.0,0.026435,Drama|Sci-Fi,Brigitte Helm,Metropolis,111841,413.0,German,6.000000,1927.0,8.3,12000,-5.973565,65.0
4033,Thomas Vinterberg,349.0,0.610968,Drama,Thomas Bo Larsen,The Hunt,170155,249.0,Danish,3.800000,2012.0,8.3,60000,-3.189032,73.0
2829,Oliver Hirschbiegel,192.0,5.501940,Biography|Drama|History|War,Thomas Kretschmann,Downfall,248354,564.0,German,13.500000,2004.0,8.3,14000,-7.998060,81.0
2551,Guillermo del Toro,406.0,37.623143,Drama|Fantasy|War,Ivana Baquero,Pan's Labyrinth,467234,1083.0,Spanish,13.500000,2006.0,8.2,27000,24.123143,86.0
4000,Juan JosÃ© Campanella,262.0,20.167424,Drama|Mystery|Thriller,Ricardo DarÃ­n,The Secret in Their Eyes,131831,231.0,Spanish,2.000000,2009.0,8.2,33000,18.167424,97.0
3550,Denis Villeneuve,226.0,6.857096,Drama|Mystery|War,Lubna Azabal,Incendies,80429,156.0,French,6.800000,2010.0,8.2,37000,0.057096,98.0
2047,Hayao Miyazaki,212.0,4.710455,Adventure|Animation|Family|Fantasy,Christian Bale,Howl's Moving Castle,214091,330.0,Japanese,24.000000,2004.0,8.2,13000,-19.289545,100.0
2830,Alejandro AmenÃ¡bar,157.0,2.086345,Biography|Drama|Romance,BelÃ©n Rueda,The Sea Inside,64556,140.0,Spanish,10.000000,2004.0,8.1,0,-7.913655,110.0
2914,Je-kyu Kang,86.0,1.110186,Action|Drama|War,Min-sik Choi,Tae Guk Gi: The Brotherhood of War,31943,224.0,Korean,12.800000,2004.0,8.1,0,-11.689814,119.0
4461,Thomas Vinterberg,98.0,1.647780,Drama,Ulrich Thomsen,The Celebration,65951,258.0,Danish,1.300000,1998.0,8.1,5000,0.347780,127.0
3553,JosÃ© Padilha,142.0,0.008060,Action|Crime|Drama|Thriller,Wagner Moura,Elite Squad,81644,107.0,Portuguese,4.000000,2007.0,8.1,11000,-3.991940,143.0
3423,Katsuhiro Ã”tomo,150.0,0.439162,Action|Animation|Sci-Fi,Mitsuo Iwata,Akira,106160,430.0,Japanese,1100.000000,1988.0,8.1,0,-1099.560838,147.0
4267,Alejandro G. IÃ±Ã¡rritu,157.0,5.383834,Drama|Thriller,Adriana Barraza,Amores Perros,173551,361.0,Spanish,2.000000,2000.0,8.1,11000,3.383834,152.0
3456,Vincent Paronnaud,242.0,4.443403,Animation|Biography|Drama|War,Catherine Deneuve,Persepolis,70194,158.0,French,7.300000,2007.0,8.0,14000,-2.856597,166.0
3344,Karan Johar,210.0,4.018695,Adventure|Drama|Thriller,Shah Rukh Khan,My Name Is Khan,69759,235.0,Hindi,12.000000,2010.0,8.0,27000,-7.981305,175.0
4144,Walter Salles,71.0,5.595428,Drama,Fernanda Montenegro,Central Station,28951,257.0,Portuguese,2.900000,1998.0,8.0,0,2.695428,177.0
4284,Ari Folman,231.0,2.283276,Animation|Biography|Documentary|Drama|History|War,Ari Folman,Waltz with Bashir,46107,156.0,Hebrew,1.500000,2008.0,8.0,0,0.783276,181.0
4897,Sergio Leone,122.0,3.500000,Action|Drama|Western,Clint Eastwood,A Fistful of Dollars,147566,235.0,Italian,0.200000,1964.0,8.0,0,3.300000,183.0
1171,Yimou Zhang,283.0,0.084961,Action|Adventure|History,Jet Li,Hero,149414,841.0,Mandarin,31.000000,2002.0,7.9,0,-30.915039,212.0
2863,Clint Eastwood,251.0,13.753931,Drama|History|War,Yuki Matsuzaki,Letters from Iwo Jima,132149,316.0,Japanese,19.000000,2006.0,7.9,5000,-5.246069,226.0
3264,Michael Haneke,447.0,0.225377,Drama|Romance,Isabelle Huppert,Amour,70382,190.0,French,8.900000,2012.0,7.9,33000,-8.674623,229.0
3510,Yash Chopra,29.0,2.921738,Drama|Musical|Romance,Shah Rukh Khan,Veer-Zaara,34449,119.0,Hindi,7.000000,2004.0,7.9,2000,-4.078262,233.0
3677,Christophe Barratier,112.0,3.629758,Drama|Music,Jean-Baptiste Maunier,The Chorus,44151,110.0,French,5.500000,2004.0,7.9,0,-1.870242,237.0
4415,FabiÃ¡n Bielinsky,94.0,1.221261,Crime|Drama|Thriller,Ricardo DarÃ­n,Nine Queens,38215,125.0,Spanish,1.500000,2000.0,7.9,0,-0.278739,243.0
4640,Cristian Mungiu,233.0,1.185783,Drama,Anamaria Marinca,"4 Months, 3 Weeks and 2 Days",44763,172.0,Romanian,0.590000,2007.0,7.9,14000,0.595783,244.0
2605,Ang Lee,287.0,128.067808,Action|Drama|Romance,Chen Chang,"Crouching Tiger, Hidden Dragon",217740,1641.0,Mandarin,15.000000,2000.0,7.9,0,113.067808,247.0

### **Find the best directors**

In [ ]:
# Extracting top 10 directors
top10_directors = df_movies.groupby('director_name').imdb_score.mean().sort_values(ascending=False).head(10)
top10_directors

director_name
Charles Chaplin          8.600000
Tony Kaye                8.600000
Alfred Hitchcock         8.500000
Ron Fricke               8.500000
Damien Chazelle          8.500000
Majid Majidi             8.500000
Sergio Leone             8.433333
Christopher Nolan        8.425000
S.S. Rajamouli           8.400000
Marius A. Markevicius    8.400000
Name: imdb_score, dtype: float64

### Find popular Genres

Extract first two genres from the genres column and store them in two new columns genre_1 and genre_2 . Some of the movies might have only one genre. In such cases, extract the single genre into both the columns.

In [ ]:
Temp_genre=df_movies.genres.str.split('|',expand=True).iloc[:,0:2]
Temp_genre.columns=['genre_1','genre_2']   # Set label to columns
Temp_genre

          genre_1    genre_2
0          Action  Adventure
1          Action  Adventure
2          Action  Adventure
3          Action   Thriller
5          Action  Adventure
...           ...        ...
5033        Drama     Sci-Fi
5034     Thriller       None
5035       Action      Crime
5037       Comedy      Drama
5042  Documentary       None

[3856 rows x 2 columns]

**Observations:** Here genre_2 column have some null values, so fill those values with genre_1 values.

In [ ]:
Temp_genre['genre_2'].fillna(Temp_genre['genre_1'],inplace=True)
Temp_genre

          genre_1      genre_2
0          Action    Adventure
1          Action    Adventure
2          Action    Adventure
3          Action     Thriller
5          Action    Adventure
...           ...          ...
5033        Drama       Sci-Fi
5034     Thriller     Thriller
5035       Action        Crime
5037       Comedy        Drama
5042  Documentary  Documentary

[3856 rows x 2 columns]

In [ ]:
# Add genres columns to movies dataframe
df_movies=pd.concat([df_movies,Temp_genre],axis=1)
df_movies

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,genre_1,genre_2
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0000,2009.0,7.9,33000,523.505847,Action,Adventure
1,Gore Verbinski,302.0,309.404152,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300.0000,2007.0,7.1,0,9.404152,Action,Adventure
2,Sam Mendes,602.0,200.074175,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245.0000,2015.0,6.8,85000,-44.925825,Action,Adventure
3,Christopher Nolan,813.0,448.130642,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250.0000,2012.0,8.5,164000,198.130642,Action,Thriller
5,Andrew Stanton,462.0,73.058679,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263.7000,2012.0,6.6,24000,-190.641321,Action,Adventure
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5033,Shane Carruth,143.0,0.424760,Drama|Sci-Fi|Thriller,Shane Carruth,Primer,72639,371.0,English,0.0070,2004.0,7.0,19000,0.417760,Drama,Sci-Fi
5034,Neill Dela Llana,35.0,0.070071,Thriller,Ian Gamazon,Cavite,589,35.0,English,0.0070,2005.0,6.3,74,0.063071,Thriller,Thriller
5035,Robert Rodriguez,56.0,2.040920,Action|Crime|Drama|Romance|Thriller,Carlos Gallardo,El Mariachi,52055,130.0,Spanish,0.0070,1992.0,6.9,0,2.033920,Action,Crime
5037,Edward Burns,14.0,0.004584,Comedy|Drama,Kerry BishÃ©,Newlyweds,1338,14.0,English,0.0090,2011.0,6.4,413,-0.004416,Comedy,Drama
5042,Jon Gunn,43.0,0.085222,Documentary,John August,My Date with Drew,4285,84.0,English,0.0011,2004.0,6.6,456,0.084122,Documentary,Documentary

**Group the dataframe using genres_1 as the primary column and genres_2 as the secondary column**

In [ ]:
df_movies.groupby(['genre_1','genre_2']).gross.mean().sort_values(ascending=False).head(5)

genre_1    genre_2
Family     Sci-Fi       434.949459
Adventure  Sci-Fi       228.627758
           Family       118.919540
           Animation    116.998550
Action     Adventure    109.595465
Name: gross, dtype: float64

**Observations:** Here family+ sci-Fi is most popular combo genres out there means it collect more amount.

### **Find the critic-favourite and audience-favourite actors**

In [ ]:
df_movies['actor_1_name'].value_counts()

Robert De Niro               42
Johnny Depp                  38
J.K. Simmons                 31
Denzel Washington            30
Nicolas Cage                 30
                             ..
Martin Dew                    1
Chriss Anglin                 1
Kevin Alejandro               1
Catherine Lough Haggquist     1
John August                   1
Name: actor_1_name, Length: 1509, dtype: int64

In [ ]:
Meryl_Streep=df_movies[df_movies['actor_1_name']=='Meryl Streep']
Leonardo_DiCaprio=df_movies[df_movies['actor_1_name']=='Leonardo DiCaprio']
Brad_Pitt=df_movies[df_movies['actor_1_name']=='Brad Pitt']

In [ ]:
combined=Brad_Pitt.append([Meryl_Streep,Leonardo_DiCaprio])
combined

<ipython-input-55-52fd1d4a30a5>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  combined=Brad_Pitt.append([Meryl_Streep,Leonardo_DiCaprio])

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,genre_1,genre_2
101,David Fincher,362.0,127.490802,Drama|Fantasy|Romance,Brad Pitt,The Curious Case of Benjamin Button,459346,822.0,English,150.0,2008.0,7.8,23000,-22.509198,Drama,Fantasy
147,Wolfgang Petersen,220.0,133.228348,Adventure,Brad Pitt,Troy,381672,1694.0,English,175.0,2004.0,7.2,0,-41.771652,Adventure,Adventure
254,Steven Soderbergh,198.0,125.531634,Crime|Thriller,Brad Pitt,Ocean's Twelve,284852,627.0,English,110.0,2004.0,6.4,0,15.531634,Crime,Thriller
255,Doug Liman,233.0,186.336103,Action|Comedy|Crime|Romance|Thriller,Brad Pitt,Mr. & Mrs. Smith,348861,798.0,English,120.0,2005.0,6.5,0,66.336103,Action,Comedy
382,Tony Scott,142.0,0.026871,Action|Crime|Thriller,Brad Pitt,Spy Game,121259,361.0,English,92.0,2001.0,7.0,0,-91.973129,Action,Crime
400,Steven Soderbergh,186.0,183.405771,Crime|Thriller,Brad Pitt,Ocean's Eleven,402645,845.0,English,85.0,2001.0,7.8,0,98.405771,Crime,Thriller
470,David Ayer,406.0,85.707116,Action|Drama|War,Brad Pitt,Fury,303185,701.0,English,68.0,2014.0,7.6,82000,17.707116,Action,Drama
611,Jean-Jacques Annaud,76.0,37.901509,Adventure|Biography|Drama|History|War,Brad Pitt,Seven Years in Tibet,96385,119.0,English,70.0,1997.0,7.0,0,-32.098491,Adventure,Biography
683,David Fincher,315.0,37.023395,Drama,Brad Pitt,Fight Club,1347461,2968.0,English,63.0,1999.0,8.8,48000,-25.976605,Drama,Drama
792,Patrick Gilmore,98.0,26.288320,Adventure|Animation|Comedy|Drama|Family|Fantas...,Brad Pitt,Sinbad: Legend of the Seven Seas,36144,91.0,English,60.0,2003.0,6.7,880,-33.711680,Adventure,Animation
940,Neil Jordan,120.0,105.264608,Drama|Fantasy|Horror,Brad Pitt,Interview with the Vampire: The Vampire Chroni...,239752,406.0,English,60.0,1994.0,7.6,11000,45.264608,Drama,Fantasy
1490,Terrence Malick,584.0,13.303319,Drama|Fantasy,Brad Pitt,The Tree of Life,136367,975.0,English,32.0,2011.0,6.7,39000,-18.696681,Drama,Fantasy
1722,Andrew Dominik,273.0,3.904982,Biography|Crime|Drama|History|Western,Brad Pitt,The Assassination of Jesse James by the Coward...,136104,415.0,English,30.0,2007.0,7.5,0,-26.095018,Biography,Crime
2204,Alejandro G. IÃ±Ã¡rritu,285.0,34.300771,Drama,Brad Pitt,Babel,243799,908.0,English,25.0,2006.0,7.5,0,9.300771,Drama,Drama
2333,Angelina Jolie Pitt,131.0,0.531009,Drama|Romance,Brad Pitt,By the Sea,7976,61.0,English,10.0,2015.0,5.3,0,-9.468991,Drama,Romance
2682,Andrew Dominik,414.0,14.938570,Crime|Thriller,Brad Pitt,Killing Them Softly,111625,369.0,English,15.0,2012.0,6.2,20000,-0.061430,Crime,Thriller
2898,Tony Scott,122.0,12.281500,Action|Crime|Drama|Romance|Thriller,Brad Pitt,True Romance,163492,460.0,English,13.0,1993.0,8.0,15000,-0.718500,Action,Crime
410,Nancy Meyers,187.0,112.703470,Comedy|Drama|Romance,Meryl Streep,It's Complicated,69860,214.0,English,85.0,2009.0,6.6,0,27.703470,Comedy,Drama
1106,Curtis Hanson,42.0,46.815748,Action|Adventure|Crime|Thriller,Meryl Streep,The River Wild,32544,69.0,English,45.0,1994.0,6.3,0,1.815748,Action,Adventure
1204,Nora Ephron,252.0,94.125426,Biography|Drama|Romance,Meryl Streep,Julie & Julia,79264,277.0,English,40.0,2009.0,7.0,13000,54.125426,Biography,Drama
1408,David Frankel,208.0,124.732962,Comedy|Drama|Romance,Meryl Streep,The Devil Wears Prada,286178,631.0,English,35.0,2006.0,6.8,0,89.732962,Comedy,Drama
1483,Robert Redford,227.0,14.998070,Drama|Thriller|War,Meryl Streep,Lions for Lambs,41170,298.0,English,35.0,2007.0,6.2,0,-20.001930,Drama,Thriller
1575,Sydney Pollack,66.0,87.100000,Biography|Drama|Romance,Meryl Streep,Out of Africa,52339,200.0,English,31.0,1985.0,7.2,0,56.100000,Biography,Drama
1618,David Frankel,234.0,63.536011,Comedy|Drama|Romance,Meryl Streep,Hope Springs,34258,178.0,English,30.0,2012.0,6.3,0,33.536011,Comedy,Drama
1674,Carl Franklin,64.0,23.209440,Drama,Meryl Streep,One True Thing,9283,112.0,English,30.0,1998.0,7.0,592,-6.790560,Drama,Drama
1925,Stephen Daldry,174.0,41.597830,Drama|Romance,Meryl Streep,The Hours,102123,660.0,English,25.0,2002.0,7.6,0,16.597830,Drama,Romance
2781,Phyllida Lloyd,331.0,29.959436,Biography|Drama|History,Meryl Streep,The Iron Lady,82327,350.0,English,13.0,2011.0,6.4,18000,16.959436,Biography,Drama
3135,Robert Altman,211.0,20.338609,Comedy|Drama|Music,Meryl Streep,A Prairie Home Companion,19655,280.0,English,10.0,2006.0,6.8,683,10.338609,Comedy,Drama
26,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.0,1997.0,7.7,26000,458.672302,Drama,Romance
50,Baz Luhrmann,490.0,144.812796,Drama|Romance,Leonardo DiCaprio,The Great Gatsby,362912,753.0,English,105.0,2013.0,7.3,115000,39.812796,Drama,Romance
97,Christopher Nolan,642.0,292.568851,Action|Adventure|Sci-Fi|Thriller,Leonardo DiCaprio,Inception,1468200,2803.0,English,160.0,2010.0,8.8,175000,132.568851,Action,Adventure
179,Alejandro G. IÃ±Ã¡rritu,556.0,183.635922,Adventure|Drama|Thriller|Western,Leonardo DiCaprio,The Revenant,406020,1188.0,English,135.0,2015.0,8.1,190000,48.635922,Adventure,Drama
257,Martin Scorsese,267.0,102.608827,Biography|Drama,Leonardo DiCaprio,The Aviator,264318,799.0,English,110.0,2004.0,7.5,0,-7.391173,Biography,Drama
296,Quentin Tarantino,765.0,162.804648,Drama|Western,Leonardo DiCaprio,Django Unchained,955174,1193.0,English,100.0,2012.0,8.5,199000,62.804648,Drama,Western
307,Edward Zwick,166.0,57.366262,Adventure|Drama|Thriller,Leonardo DiCaprio,Blood Diamond,400292,657.0,English,100.0,2006.0,8.0,14000,-42.633738,Adventure,Drama
308,Martin Scorsese,606.0,116.866727,Biography|Comedy|Crime|Drama,Leonardo DiCaprio,The Wolf of Wall Street,780588,1138.0,English,100.0,2013.0,8.2,138000,16.866727,Biography,Comedy
326,Martin Scorsese,233.0,77.679638,Crime|Drama,Leonardo DiCaprio,Gangs of New York,314033,1166.0,English,100.0,2002.0,7.5,0,-22.320362,Crime,Drama
361,Martin Scorsese,352.0,132.373442,Crime|Drama|Thriller,Leonardo DiCaprio,The Departed,873649,2054.0,English,90.0,2006.0,8.5,29000,42.373442,Crime,Drama
452,Martin Scorsese,490.0,127.968405,Mystery|Thriller,Leonardo DiCaprio,Shutter Island,786092,964.0,English,80.0,2010.0,8.1,53000,47.968405,Mystery,Thriller
641,Ridley Scott,238.0,39.380442,Action|Drama|Thriller,Leonardo DiCaprio,Body of Lies,174248,263.0,English,70.0,2008.0,7.1,0,-30.619558,Action,Drama
911,Steven Spielberg,194.0,164.435221,Biography|Crime|Drama,Leonardo DiCaprio,Catch Me If You Can,525801,667.0,English,52.0,2002.0,8.0,15000,112.435221,Biography,Crime
990,Danny Boyle,118.0,39.778599,Adventure|Drama|Thriller,Leonardo DiCaprio,The Beach,176169,548.0,English,50.0,2000.0,6.6,0,-10.221401,Adventure,Drama
1114,Sam Mendes,323.0,22.877808,Drama|Romance,Leonardo DiCaprio,Revolutionary Road,152591,414.0,English,35.0,2008.0,7.3,0,-12.122192,Drama,Romance
1422,Randall Wallace,83.0,56.876365,Action|Adventure,Leonardo DiCaprio,The Man in the Iron Mask,125219,244.0,English,35.0,1998.0,6.4,0,21.876365,Action,Adventure
1453,Clint Eastwood,392.0,37.304950,Biography|Crime|Drama,Leonardo DiCaprio,J. Edgar,102728,279.0,English,35.0,2011.0,6.6,16000,2.304950,Biography,Crime
1560,Sam Raimi,63.0,18.636537,Action|Thriller|Western,Leonardo DiCaprio,The Quick and the Dead,69197,216.0,English,32.0,1995.0,6.4,0,-13.363463,Action,Thriller
2067,Jerry Zaks,45.0,12.782508,Drama,Leonardo DiCaprio,Marvin's Room,20163,71.0,English,23.0,1996.0,6.7,1000,-10.217492,Drama,Drama
2757,Baz Luhrmann,106.0,46.338728,Drama|Romance,Leonardo DiCaprio,Romeo + Juliet,167750,506.0,English,14.5,1996.0,6.8,10000,31.838728,Drama,Romance
3476,Baz Luhrmann,490.0,144.812796,Drama|Romance,Leonardo DiCaprio,The Great Gatsby,362933,753.0,English,105.0,2013.0,7.3,115000,39.812796,Drama,Romance

In [ ]:
combined.groupby('actor_1_name').num_critic_for_reviews.mean()

actor_1_name
Brad Pitt            245.000000
Leonardo DiCaprio    330.190476
Meryl Streep         181.454545
Name: num_critic_for_reviews, dtype: float64

In [ ]:
combined.groupby('actor_1_name').num_user_for_reviews.mean()

actor_1_name
Brad Pitt            742.352941
Leonardo DiCaprio    914.476190
Meryl Streep         297.181818
Name: num_user_for_reviews, dtype: float64

In [ ]:
# Alternate way to find mean for both columns
combined.groupby('actor_1_name')[['num_user_for_reviews','num_critic_for_reviews']].mean()

                   num_user_for_reviews  num_critic_for_reviews
actor_1_name
Brad Pitt                    742.352941              245.000000
Leonardo DiCaprio            914.476190              330.190476
Meryl Streep                 297.181818              181.454545

**Observations:** Above from two lists Leonardo DiCapriogot high reviews.

https://www.youtube.com/watch?v=lFGtBC2MG8Y  -Reference link